# Generated by Django 6.0.7 on 2026-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('datOfBirth', models.DateField()),
                ('city', models.CharField(max_length=120)),
                ('user_password', models.CharField(max_length=120)),
            ],
        ),
    ]
