# Generated by Django 6.0.7 on 2026-07-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='datOfBirth',
            new_name='dateOfBirth',
        ),
    ]
