# Generated by Django 6.0.7 on 2026-07-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_registration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
