# Generated by Django 6.0.7 on 2026-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_registration_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('motherName', models.CharField(max_length=120)),
                ('fatherName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('pincode', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
