# Generated by Django 6.0.7 on 2026-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
    ]
